name: research-map
channels:
  - defaults
dependencies:
  - r-fields
  - r-ggalt
  - r-gridextra
  - r-ggrepel=0.8.0
  - seaborn=0.9.0
  - python=3.7.1
  - r-hrbrthemes
  - umap-learn=0.3.7
  - matplotlib=3.0.2
  - r-plyr
  - r-base=3.5.1
  - notebook
  - metaknowledge=3.3.2
  - rpy2=2.9.1
  - r-stringr=1.3.1
  - hdbscan=0.8.18
  - r-ggplot2=3.0.0
  - simplegeneric=0.8.1
  - pandas=0.23.4
  - r-ggforce
  - scikit-learn=0.20.2
  - scipy=1.2.0
  - numba=0.41.0
  - r-clue=0.3_57
  - ipysankeywidget